### PR TITLE
Even more catching up and some fixes.

### PR DESCRIPTION
**Pull request by MagnetarRocket**
I have been out an while, adjusted menubar naming to be in line with common motif app standards(Setting *menuBar in xdefaults should work uniformly with motif apps in general) and added in a start to non-fixed HTML help locations(Attempting to not trust the old defaults as package managers my be silly in putting down spots), also had to put in an correction to the first commit.

### CODE REVIEW

**Comment by rpendleton** [comment]
It looks like you're cherry-picking merge commits into your repo in order to get up-to-date with Justin's repo. This leads to noisy commits and can make it hard to determine which commits actually introduced changes when viewing PRs. (It's also not very practical long-term, since it means you'd need to cherry-pick every single PR that's merged to this upstream repo to keep your fork up-to-date.)

Rather than cherry-picking merge commits into your branch to catch up, it would be better to simply rebase your branch on the upstream master branch.

**Comment by MagnetarRocket** [comment]
How to rebase?

**Comment by rpendleton** [comment]
This StackOverflow answer provides a decent explanation of how to do a rebase from a GitHub fork:

[How do I update or sync a forked repository on GitHub?](https://stackoverflow.com/a/7244456/425782)

**Comment by justinmeiners** [comment]
@MagnetarRocket Good to see you back! Ryan will be helping me out.

- Let's file an issue for the help path, since we don't have a solution yet.
- Only the string needs to change. defaults can't "see" the C variable names.

**Comment by rpendleton** [comment]
I cherry-picked the string part of the `"menubar"` -> `"menuBar"` change into master, which closes this PR.

As for the hard-coded help path, it looks like #32 has already been created for that.

**Pull request closed without merging**
