### PR TITLE
A pull request

### PR DESCRIPTION
**Pull request by MagnetarRocket**
Add HTML-help, adding graphicsmagick to the build icons requirements, a mac os screenshot, and a Shapes Icon

### CODE REVIEW

**Comment by justinmeiners** [comment]
I appreciate the contribution. I am noticing some changes as you go so let me know when it's ready.


Here are some thoughts:
- we also support .tga and .bmp (now fixed).
- does this help html tie into the system in anyway? If not, I would prefer the folder to be called "docs/"
- If you have any better suggestions for tool tips, please make the change in the code.

**Comment by justinmeiners** [comment]
Any update for me on this, or still working?

**Comment by MagnetarRocket** [comment]
A review, my thoughts on what you said are:

> I appreciate the contribution. I am noticing some changes as you go so let me know when it's ready.
> 
> Here are some thoughts:
> 
> * we also support .tga and .bmp (now fixed).
> * does this help html tie into the system in anyway? If not, I would prefer the folder to be called `docs/` or `help/`. Should we install this with the program in a standard unix location?
> * If you have any better suggestions for tool tips, please make the change in the code.
> * What is the plan for the shapes icon?

- added both those in the readmes (The HTML one and the manpage mockup)

-altered the directory name to "help"; may put the HTML help page on a separate site, unix traditionally does not have HTML help pages. may need to turrn the manpage mockup (classic-colors.1) into a proper manpage. (Linux users often insist on manpages)

-Tooltips? my main thought was of an simple legacy HTML compatible help page accessed from the help section of the menu, now when i searched on motif's support on tooltips, it's a late addition and was not in the unix versions at all until 2002. alas documentation on tooltips may be scant. 

mockup of what i'm thinking about:
HelpMockup

-Actually, i found out you had: ( https://github.com/justinmeiners/classic-colors/issues/1 ) , however i might do that in a separate pull request as that was a first draft and i removed the PolygonShapes icons from this pull request.

**Comment by justinmeiners** [comment]
Looks good! I am really grateful for making this better.
I have some edits, but am going to merge it it.

> my main thought was of an simple legacy HTML compatible help page

I added a submenu to help that opens this page. Great idea. Love the classic look.

> PolygonShapes

A separate PR would be good. I need to get around to programming that feature too!

> manpage mockup

Makes sense. I like the HTML but am unsure how useful a detailed man page would be.
I think the man page should just tell them about the command line options, provide author and website information, and direct them to the HTML.

**Pull request merged**
