### PR TITLE
Adjust image and add the beginnings to compiling on Tribblix.

### PR DESCRIPTION
**Pull request by MagnetarRocket**
Adjusted HTML help to add in new images as needed and add the beginnings of how to install on openIndiana/Tribblix in README because Peter Tribble did so? https://twitter.com/ptribble/status/1555532045031510016 (was trying to get help running a openIndiana VM on a M1 MacBook air just for testing and one suggested app was classic-paint, and then that happened)

### CODE REVIEW

**Comment by justinmeiners** [comment]
Looking good! I have never heard of openindiana or tribblix haha. Generally I think its a good idea to add `configure` support for any platform someone wants to use (within reason). I would focus the README a bit more though. People on obscure platforms know what they need to do. In this case, can we just provide solaris instructions and those will work? Or is tribblix completely different?

**Comment by MagnetarRocket** [comment]
Tribblix and openindiana are production ready forks of illumos, illumos is the only actively developed fork of OpenSolaris left after oracle dropped development of it to great uproar. 

Name might be "SunOS" as in alx210's stuff or "Solaris" as most people would refer to those two and should in theory be compilable on modern Solaris, names your pick, but Mr Tribble did not state the steps needed in the tweet, just that it went without a hitch and somebody stating that back in the day they reformatted solaris's x11 libraries to be more standardized in line with modern xOrg.

**Comment by ptribble** [comment]
The only change I made was to

sed -i s:/usr/local/share/classic-colors/help:/usr/share/classic-colors/help: ui_main.c

because I don't package anything in /usr/local. (Ideally that would be derived from PREFIX rather that hard-coded.)

But to build all that was necessary on Tribblix was "./configure && gmake". No changes necessary. (And I now ship a ready built package.)

**Comment by justinmeiners** [comment]
I am excited to get the help updates in here. Should we merge it in now and add more to the install README later, or do you have more plans?

**Comment by MagnetarRocket** [comment]
The images can be pushed, readme may be updated later in the future when i can get a working illumos distro up and running, will update on my own fork of changes i may intend to push in the future.

**Comment by justinmeiners** [comment]
@MagnetarRocket thanks again for your support! Sorry for slow responses.

**Pull request merged**
