### PR TITLE
minor2

### PR DESCRIPTION
**Pull request by MagnetarRocket**
Major alterations for the html-help (images not yet updated, would get around to that down the road), and the "icon_polygon-select2" icon being renamed the more descriptive "icon_lasso". If the aim is to be close to 9x paint, i'm fine with that. (but a little disappointed for true polygon select not being implemented)

### CODE REVIEW

**Comment by justinmeiners** [comment]
Thanks so much!

> but a little disappointed for true polygon select not being implemented

Do you mean that you prefer to draw the selection box, just like you draw the polygon one point at a time?

**Comment by MagnetarRocket** [comment]
One polygon point at a time, but lasso's still useful for situations that require a loose selection.

**Comment by MagnetarRocket** [comment]
whoops again, should try to make private branch a part of my habit, but a curved line function wold be nice.

**Comment by justinmeiners** [comment]
Thanks for updating the documentation. Still considering what tools to do next.

**Pull request merged**
